basePath: /api
definitions:
  domain.IngredientDetail:
    properties:
      ingredient_less_than:
        type: integer
      ingredient_name:
        type: string
      ingredient_quantity:
        type: string
      ingredient_url:
        items:
          type: string
        type: array
      stock_amount:
        type: integer
      stocks:
        items:
          $ref: '#/definitions/domain.Stock'
        type: array
    type: object
  domain.IngredientNote:
    properties:
      ingredient_note:
        type: string
      ingredient_note_id:
        type: string
      note_created_at:
        type: string
    type: object
  domain.IngredientStockDetail:
    properties:
      day_before_expire:
        type: string
      ingredient_brand:
        type: string
      ingredient_eng_name:
        type: string
      ingredient_price:
        type: string
      ingredient_quantity:
        type: string
      ingredient_stock_url:
        type: string
      ingredient_supplier:
        type: string
      ingredient_thai_name:
        type: string
      notes:
        items:
          $ref: '#/definitions/domain.IngredientNote'
        type: array
    type: object
  domain.RecipeDetail:
    properties:
      instruction_steps:
        items:
          type: string
        type: array
      instruction_url:
        items:
          type: string
        type: array
      num_of_order:
        type: integer
      recipe_ingredients:
        items:
          $ref: '#/definitions/domain.RecipeIngredient'
        type: array
      recipe_name:
        type: string
      recipe_url:
        items:
          type: string
        type: array
      servings:
        type: integer
      stars:
        type: integer
      status:
        type: integer
      total_time:
        type: string
    type: object
  domain.RecipeIngredient:
    properties:
      ingredient_name:
        type: string
      ingredient_price:
        type: number
      ingredient_quantity:
        type: string
      ingredient_url:
        type: string
    type: object
  domain.Stock:
    properties:
      expiration_date:
        type: string
      expiration_status:
        type: string
      price:
        type: string
      quantity:
        type: string
      stock_id:
        type: string
      stock_url:
        type: string
    type: object
  domain.StockDetail:
    properties:
      created_at:
        type: string
      lst_status:
        type: string
      quantity:
        type: integer
      sell_by_date:
        type: string
    type: object
  http.response:
    properties:
      data: {}
      error:
        type: string
      message:
        example: Success
        type: string
      status:
        example: 200
        type: integer
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is the BakingUp Backend API.
  title: BakingUp Backend API
  version: "1.0"
paths:
  /ingredient/deleteIngredientBatchNote:
    delete:
      consumes:
      - application/json
      description: Delete ingredient batch note by ingredient note ID
      parameters:
      - description: Ingredient Note ID
        in: query
        name: ingredient_note_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot delete ingredient batch note
          schema:
            $ref: '#/definitions/http.response'
      summary: Delete ingredient batch note
      tags:
      - ingredient
  /ingredient/getIngredientDetail:
    get:
      consumes:
      - application/json
      description: Get ingredient details by ingredient ID
      parameters:
      - description: Ingredient ID
        in: query
        name: ingredient_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.IngredientDetail'
        "400":
          description: Cannot get ingredient detail
          schema:
            $ref: '#/definitions/http.response'
      summary: Get ingredient details
      tags:
      - ingredient
  /ingredient/getIngredientStockDetail:
    get:
      consumes:
      - application/json
      description: Get ingredient stock details by ingredient stock ID
      parameters:
      - description: Ingredient stock ID
        in: query
        name: ingredient_stock_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.IngredientStockDetail'
        "400":
          description: Cannot get ingredient stock detail
          schema:
            $ref: '#/definitions/http.response'
      summary: Get ingredient stock details
      tags:
      - ingredient
  /recipe/deleteRecipe:
    delete:
      consumes:
      - application/json
      description: Delete a recipe by using recipe id
      parameters:
      - description: Recipe ID
        in: query
        name: recipe_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot delete a recipe
          schema:
            $ref: '#/definitions/http.response'
      summary: Delete a recipe
      tags:
      - recipe
  /recipe/getRecipeDetail:
    get:
      consumes:
      - application/json
      description: Get recipe details by recipe ID
      parameters:
      - description: Recipe ID
        in: query
        name: recipe_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.RecipeDetail'
        "400":
          description: Cannot get recipe detail
          schema:
            $ref: '#/definitions/http.response'
      summary: Get recipe details
      tags:
      - recipe
  /stock/deleteStock:
    delete:
      consumes:
      - application/json
      description: Delete a stock by recipe id
      parameters:
      - description: Recipe ID
        in: query
        name: recipe_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot delete a stock
          schema:
            $ref: '#/definitions/http.response'
      summary: Delete a stock
      tags:
      - stock
  /stock/getStockDetail:
    get:
      consumes:
      - application/json
      description: Get stock details by recipe ID and user ID
      parameters:
      - description: Recipe ID
        in: query
        name: recipe_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.StockDetail'
        "400":
          description: Cannot get stock detail
          schema:
            $ref: '#/definitions/http.response'
      summary: Get stock details
      tags:
      - stock
swagger: "2.0"
