basePath: /api
definitions:
  domain.ChangeExpirationDateSetting:
    properties:
      black_expiration_date:
        type: integer
      red_expiration_date:
        type: integer
      user_id:
        type: string
      yellow_expiration_date:
        type: integer
    type: object
  domain.ChangeFixCostSetting:
    properties:
      advertising:
        type: number
      electricity:
        type: number
      gas:
        type: number
      insurance:
        type: number
      note:
        type: string
      other:
        type: number
      rent:
        type: number
      salaries:
        type: number
      subscriptions:
        type: number
      user_id:
        type: string
      water:
        type: number
    type: object
  domain.ChangeUserLanguage:
    properties:
      language:
        type: string
      user_id:
        type: string
    type: object
  domain.ExpirationDateSetting:
    properties:
      black_expiration_date:
        type: integer
      red_expiration_date:
        type: integer
      yellow_expiration_date:
        type: integer
    type: object
  domain.FixCostSetting:
    properties:
      advertising:
        type: number
      electricity:
        type: number
      gas:
        type: number
      insurance:
        type: number
      note:
        type: string
      other:
        type: number
      rent:
        type: number
      salaries:
        type: number
      subscriptions:
        type: number
      water:
        type: number
    type: object
  domain.Ingredient:
    properties:
      expiration_status:
        type: string
      ingredient_id:
        type: string
      ingredient_name:
        type: string
      ingredient_url:
        type: string
      quantity:
        type: string
      stock:
        type: integer
    type: object
  domain.IngredientDetail:
    properties:
      ingredient_less_than:
        type: integer
      ingredient_name:
        type: string
      ingredient_quantity:
        type: string
      ingredient_url:
        items:
          type: string
        type: array
      stock_amount:
        type: integer
      stocks:
        items:
          $ref: '#/definitions/domain.Stock'
        type: array
    type: object
  domain.IngredientList:
    properties:
      ingredients:
        items:
          $ref: '#/definitions/domain.Ingredient'
        type: array
    type: object
  domain.IngredientNote:
    properties:
      ingredient_note:
        type: string
      ingredient_note_id:
        type: string
      note_created_at:
        type: string
    type: object
  domain.IngredientStockDetail:
    properties:
      day_before_expire:
        type: string
      ingredient_brand:
        type: string
      ingredient_eng_name:
        type: string
      ingredient_price:
        type: string
      ingredient_quantity:
        type: string
      ingredient_stock_url:
        type: string
      ingredient_supplier:
        type: string
      ingredient_thai_name:
        type: string
      notes:
        items:
          $ref: '#/definitions/domain.IngredientNote'
        type: array
    type: object
  domain.ManageUserRequest:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      store_name:
        type: string
      tel:
        type: string
      user_id:
        type: string
    type: object
  domain.RecipeDetail:
    properties:
      instruction_steps:
        items:
          type: string
        type: array
      instruction_url:
        items:
          type: string
        type: array
      num_of_order:
        type: integer
      recipe_ingredients:
        items:
          $ref: '#/definitions/domain.RecipeIngredient'
        type: array
      recipe_name:
        type: string
      recipe_url:
        items:
          type: string
        type: array
      servings:
        type: integer
      stars:
        type: integer
      status:
        type: integer
      total_time:
        type: string
    type: object
  domain.RecipeIngredient:
    properties:
      ingredient_name:
        type: string
      ingredient_price:
        type: number
      ingredient_quantity:
        type: string
      ingredient_url:
        type: string
    type: object
  domain.Stock:
    properties:
      expiration_date:
        type: string
      expiration_status:
        type: string
      price:
        type: string
      quantity:
        type: string
      stock_id:
        type: string
      stock_url:
        type: string
    type: object
  domain.StockDetail:
    properties:
      created_at:
        type: string
      lst_status:
        type: string
      quantity:
        type: integer
      sell_by_date:
        type: string
    type: object
  domain.UserLanguage:
    properties:
      language:
        type: string
    type: object
  http.response:
    properties:
      data: {}
      error:
        type: string
      message:
        example: Success
        type: string
      status:
        example: 200
        type: integer
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is the BakingUp Backend API.
  title: BakingUp Backend API
  version: "1.0"
paths:
  /ingredient/deleteIngredient:
    delete:
      consumes:
      - application/json
      description: Delete an ingredient by using ingredient id
      parameters:
      - description: Ingredient ID
        in: query
        name: ingredient_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot delete an ingredient
          schema:
            $ref: '#/definitions/http.response'
      summary: Delete an ingredient
      tags:
      - ingredient
  /ingredient/deleteIngredientBatchNote:
    delete:
      consumes:
      - application/json
      description: Delete ingredient batch note by ingredient note ID
      parameters:
      - description: Ingredient Note ID
        in: query
        name: ingredient_note_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot delete ingredient batch note
          schema:
            $ref: '#/definitions/http.response'
      summary: Delete ingredient batch note
      tags:
      - ingredient
  /ingredient/getAllIngredients:
    get:
      consumes:
      - application/json
      description: Get all ingredients by user ID
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.IngredientList'
        "400":
          description: Cannot get all ingredients
          schema:
            $ref: '#/definitions/http.response'
      summary: Get all ingredients
      tags:
      - ingredient
  /ingredient/getIngredientDetail:
    get:
      consumes:
      - application/json
      description: Get ingredient details by ingredient ID
      parameters:
      - description: Ingredient ID
        in: query
        name: ingredient_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.IngredientDetail'
        "400":
          description: Cannot get ingredient detail
          schema:
            $ref: '#/definitions/http.response'
      summary: Get ingredient details
      tags:
      - ingredient
  /ingredient/getIngredientStockDetail:
    get:
      consumes:
      - application/json
      description: Get ingredient stock details by ingredient stock ID
      parameters:
      - description: Ingredient stock ID
        in: query
        name: ingredient_stock_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.IngredientStockDetail'
        "400":
          description: Cannot get ingredient stock detail
          schema:
            $ref: '#/definitions/http.response'
      summary: Get ingredient stock details
      tags:
      - ingredient
  /recipe/deleteRecipe:
    delete:
      consumes:
      - application/json
      description: Delete a recipe by using recipe id
      parameters:
      - description: Recipe ID
        in: query
        name: recipe_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot delete a recipe
          schema:
            $ref: '#/definitions/http.response'
      summary: Delete a recipe
      tags:
      - recipe
  /recipe/getRecipeDetail:
    get:
      consumes:
      - application/json
      description: Get recipe details by recipe ID
      parameters:
      - description: Recipe ID
        in: query
        name: recipe_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.RecipeDetail'
        "400":
          description: Cannot get recipe detail
          schema:
            $ref: '#/definitions/http.response'
      summary: Get recipe details
      tags:
      - recipe
  /settings/changeColorExpired:
    put:
      consumes:
      - application/json
      description: Change the color of expired icon by user id
      parameters:
      - description: Change Color Expired Icon
        in: body
        name: change_color_expired_icon
        required: true
        schema:
          $ref: '#/definitions/domain.ChangeExpirationDateSetting'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully change the color of expiration icon
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot change the color of expiration icon
          schema:
            $ref: '#/definitions/http.response'
      summary: Change the color of expired icon
      tags:
      - settings
  /settings/changeFixCost:
    put:
      consumes:
      - application/json
      description: Change the fix cost by user id
      parameters:
      - description: Change Fix Cost
        in: body
        name: change_fix_cost
        required: true
        schema:
          $ref: '#/definitions/domain.ChangeFixCostSetting'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully change the fix cost
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot change the fix cost
          schema:
            $ref: '#/definitions/http.response'
      summary: Change the fix cost
      tags:
      - settings
  /settings/changeLanguage:
    put:
      consumes:
      - application/json
      description: Change the application language by user id
      parameters:
      - description: Change Language
        in: body
        name: change_language
        required: true
        schema:
          $ref: '#/definitions/domain.ChangeUserLanguage'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully change the language.
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot change the language
          schema:
            $ref: '#/definitions/http.response'
      summary: Change the application language
      tags:
      - settings
  /settings/deleteAccount:
    delete:
      consumes:
      - application/json
      description: Delete an account by user id
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully delete an account
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot delete an account
          schema:
            $ref: '#/definitions/http.response'
      summary: Delete an account
      tags:
      - settings
  /settings/getColorExpired:
    get:
      consumes:
      - application/json
      description: Get the color of expired icon by user id
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.ExpirationDateSetting'
        "400":
          description: Cannot get the color of expiration icon
          schema:
            $ref: '#/definitions/http.response'
      summary: Get the color of expired icon
      tags:
      - settings
  /settings/getFixCost:
    get:
      consumes:
      - application/json
      description: Get the fix cost by user id
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.FixCostSetting'
        "400":
          description: Cannot get the fix cost
          schema:
            $ref: '#/definitions/http.response'
      summary: Get the fix cost
      tags:
      - settings
  /settings/getLanguage:
    get:
      consumes:
      - application/json
      description: Get the application language by user id
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.UserLanguage'
        "400":
          description: Cannot get the language
          schema:
            $ref: '#/definitions/http.response'
      summary: Get the application language
      tags:
      - settings
  /stock/deleteStock:
    delete:
      consumes:
      - application/json
      description: Delete a stock by recipe id
      parameters:
      - description: Recipe ID
        in: query
        name: recipe_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot delete a stock
          schema:
            $ref: '#/definitions/http.response'
      summary: Delete a stock
      tags:
      - stock
  /stock/getStockDetail:
    get:
      consumes:
      - application/json
      description: Get stock details by recipe ID and user ID
      parameters:
      - description: Recipe ID
        in: query
        name: recipe_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/domain.StockDetail'
        "400":
          description: Cannot get stock detail
          schema:
            $ref: '#/definitions/http.response'
      summary: Get stock details
      tags:
      - stock
  /user/editUserInfo:
    put:
      consumes:
      - application/json
      description: Edit user information by using user information request
      parameters:
      - description: Edit User Info
        in: body
        name: edit_user_info
        required: true
        schema:
          $ref: '#/definitions/domain.ManageUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully edit the user information.
          schema:
            $ref: '#/definitions/http.response'
        "400":
          description: Cannot edit the user information
          schema:
            $ref: '#/definitions/http.response'
      summary: Edit user information
      tags:
      - user
swagger: "2.0"
