basePath: /api
definitions:
  domain.Stock:
    properties:
      expiration_date:
        type: string
      expiration_status:
        type: string
      price:
        type: string
      quantity:
        type: string
      stock_id:
        type: string
      stock_url:
        type: string
    type: object
  http.IngredientDetail:
    properties:
      ingredient_less_than:
        type: integer
      ingredient_name:
        type: string
      ingredient_quantity:
        type: string
      ingredient_url:
        items:
          type: string
        type: array
      stock_amount:
        type: integer
      stocks:
        items:
          $ref: '#/definitions/domain.Stock'
        type: array
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is the BakingUp Backend API.
  title: BakingUp Backend API
  version: "1.0"
paths:
  /ingredient/{ingredientID}:
    get:
      consumes:
      - application/json
      description: Get ingredient details by ingredient ID
      parameters:
      - description: Ingredient ID
        in: path
        name: ingredientID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            $ref: '#/definitions/http.IngredientDetail'
      summary: Get ingredient details
      tags:
      - ingredient
swagger: "2.0"
