name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.6'

      - name: Install Go dependencies
        run: go mod download

      - name: Run Go tests
        run: go test -v ./...
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HTTP_PORT: 8000
      
      - name: Login to docker
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Env file
        run: echo '${{secrets.BACKEND_PRODUCTION_ENV}}' > .env

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bakingup-backend:latest
    
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SSH_HOST }}
          username: ${{ secrets.PRODUCTION_SSH_USERNAME }}
          password: ${{ secrets.PRODUCTION_SSH_PASSWORD }}
          script: |
            cd bakingUp
            docker pull ${{ secrets.DOCKER_USERNAME }}/bakingup-backend:latest
            docker-compose up --detach 
            docker system prune -af
  
